### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [juliagviu/ComputerGraphics#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/116841016-6a6b4f00-ac0a-11eb-9ba1-a19c64aab810.png)

thank you  
best regards to you  
William

**Comment by juliagviu** [comment]
Hi,
Thanks for your question. I am sorry but Photon Mapping cannot be built. Those compiled libraries that are required (all under objects/ dir) are not our property, as they were given to us as base code for the course. We published only our own source files, but the project is not thought to be built or run.

Path Tracer code was fully written by us and all requirements to compile and run it should be there, in case you are interested :)

best,
Julia
